# Generated by Django 6.0.4 on 2026-04-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_employmentrequest_profile_delete_tourist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentrequest',
            old_name='created_ar',
            new_name='created_at',
        ),
    ]
