# Generated by Django 6.0.4 on 2026-04-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_rating_alter_employmentrequest_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentrequest',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='api.profile'),
        ),
    ]
